# Generated by Django 2.2.17 on 2021-09-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dpic',
            new_name='pic',
        ),
    ]
